CREATE TABLE IF NOT EXISTS users (
    user_id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    username VARCHAR(50) NOT NULL UNIQUE,
    firstname VARCHAR(50) NOT NULL,
    lastname VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS planets (
    planet_id INT AUTO_INCREMENT PRIMARY KEY,

);

CREATE TABLE IF NOT EXISTS species (

);

CREATE TABLE IF NOT EXISTS tags (

);